[[XyceWrapper]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6287f37a8b374f5de1281a151e4f60851601d7a7"
libc = "glibc"
os = "linux"

    [[XyceWrapper.download]]
    sha256 = "e05d05ef68a71707ae63ef646a9cc24563528c56e7cc74b6e3ac069021b74193"
    url = "https://github.com/JuliaBinaryWrappers/XyceWrapper_jll.jl/releases/download/XyceWrapper-v0.1.1+0/XyceWrapper.v0.1.1.aarch64-linux-gnu-cxx03.tar.gz"
[[XyceWrapper]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "85d6924785d99a2e2837697049ecd3c7c9e3ccfc"
libc = "glibc"
os = "linux"

    [[XyceWrapper.download]]
    sha256 = "e16327f3258f0a4c5526e7070459eed9378d258e0154e9a7f5e21c80272116fa"
    url = "https://github.com/JuliaBinaryWrappers/XyceWrapper_jll.jl/releases/download/XyceWrapper-v0.1.1+0/XyceWrapper.v0.1.1.aarch64-linux-gnu-cxx11.tar.gz"
[[XyceWrapper]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "289f4a20a7bf89898718abf6d4e4a02e2eb0ad79"
libc = "musl"
os = "linux"

    [[XyceWrapper.download]]
    sha256 = "9a9ac0f97b11a332b7b40e04451849d0cea949f13fd3f7d63e746d79b756f8c0"
    url = "https://github.com/JuliaBinaryWrappers/XyceWrapper_jll.jl/releases/download/XyceWrapper-v0.1.1+0/XyceWrapper.v0.1.1.aarch64-linux-musl-cxx03.tar.gz"
[[XyceWrapper]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1db57c76699348c5f6e3309743674abd41e35821"
libc = "musl"
os = "linux"

    [[XyceWrapper.download]]
    sha256 = "5e78c25a3499d975a8ed6f584c5b22764e6b71ac42f6eff351d7258412eeee5b"
    url = "https://github.com/JuliaBinaryWrappers/XyceWrapper_jll.jl/releases/download/XyceWrapper-v0.1.1+0/XyceWrapper.v0.1.1.aarch64-linux-musl-cxx11.tar.gz"
[[XyceWrapper]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fbd602e4d1dd0172f8c7e7639baa7e77ff6bcc1a"
libc = "glibc"
os = "linux"

    [[XyceWrapper.download]]
    sha256 = "d0aa718731292491fb5ace84cc019dfc0f84cf8b7f9b5c9a29618934d8df14fa"
    url = "https://github.com/JuliaBinaryWrappers/XyceWrapper_jll.jl/releases/download/XyceWrapper-v0.1.1+0/XyceWrapper.v0.1.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[XyceWrapper]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "386571ae14b26318fa89842e83c8ebdd9ecb7b6d"
libc = "glibc"
os = "linux"

    [[XyceWrapper.download]]
    sha256 = "2a7ef569183d5ce3947f0a62c36e47e927317cdd5aac7c7430c42962b176fba9"
    url = "https://github.com/JuliaBinaryWrappers/XyceWrapper_jll.jl/releases/download/XyceWrapper-v0.1.1+0/XyceWrapper.v0.1.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[XyceWrapper]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9200cd872f70962d8dc5e821c77550ca4fc76b80"
libc = "musl"
os = "linux"

    [[XyceWrapper.download]]
    sha256 = "bd1d6b7a2819ec5e2930b0edafb3c22f4697c9be3970c601069c19ba6750429e"
    url = "https://github.com/JuliaBinaryWrappers/XyceWrapper_jll.jl/releases/download/XyceWrapper-v0.1.1+0/XyceWrapper.v0.1.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[XyceWrapper]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8c577d7ae11e3bcdb1b88c205d44eb8fd2881195"
libc = "musl"
os = "linux"

    [[XyceWrapper.download]]
    sha256 = "83a86fb9fac290546be4669161c1e683e699bb71eca424a3a25860e35594185e"
    url = "https://github.com/JuliaBinaryWrappers/XyceWrapper_jll.jl/releases/download/XyceWrapper-v0.1.1+0/XyceWrapper.v0.1.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[XyceWrapper]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "53c9e949b931cb7218b7c9ed405bc5c32900e2f0"
libc = "glibc"
os = "linux"

    [[XyceWrapper.download]]
    sha256 = "85ddcf3db0036538fc668efb586a6245bee2105afaee3d3ebb3b0107c25437cc"
    url = "https://github.com/JuliaBinaryWrappers/XyceWrapper_jll.jl/releases/download/XyceWrapper-v0.1.1+0/XyceWrapper.v0.1.1.i686-linux-gnu-cxx03.tar.gz"
[[XyceWrapper]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "619edb63c1407cd4f5c48502c5259ee43b95022f"
libc = "glibc"
os = "linux"

    [[XyceWrapper.download]]
    sha256 = "af9dc681752aab85cc1f98d1dbb77d174e462ead2cb692446a012137f7853c09"
    url = "https://github.com/JuliaBinaryWrappers/XyceWrapper_jll.jl/releases/download/XyceWrapper-v0.1.1+0/XyceWrapper.v0.1.1.i686-linux-gnu-cxx11.tar.gz"
[[XyceWrapper]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "aa99ccfbefb0b01aee8c217240f97d83d0b4d8b4"
libc = "glibc"
os = "linux"

    [[XyceWrapper.download]]
    sha256 = "3adbfe7c592511cf4ae19a97f641db8f65bce6ce4dc10a5397465d3d0630f96e"
    url = "https://github.com/JuliaBinaryWrappers/XyceWrapper_jll.jl/releases/download/XyceWrapper-v0.1.1+0/XyceWrapper.v0.1.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[XyceWrapper]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "be60dac4d1cd0b601e5e681f70b53e3076e044e6"
libc = "glibc"
os = "linux"

    [[XyceWrapper.download]]
    sha256 = "1eb02d60879a3eef6f0bd718f88a641c8561af1fe27f3e0c7bcaa24bec93efcc"
    url = "https://github.com/JuliaBinaryWrappers/XyceWrapper_jll.jl/releases/download/XyceWrapper-v0.1.1+0/XyceWrapper.v0.1.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[XyceWrapper]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "cefe98408d34120f37f6ef4cbe73216d3b8aaa93"
libc = "glibc"
os = "linux"

    [[XyceWrapper.download]]
    sha256 = "b71cbf654bc4bb03815cea2883f5548f3dd72b91d57e58e957a54462ab22b5ff"
    url = "https://github.com/JuliaBinaryWrappers/XyceWrapper_jll.jl/releases/download/XyceWrapper-v0.1.1+0/XyceWrapper.v0.1.1.x86_64-linux-gnu-cxx03.tar.gz"
[[XyceWrapper]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f7a016b80a681bae77a9550512d7e65435aafde5"
libc = "glibc"
os = "linux"

    [[XyceWrapper.download]]
    sha256 = "985828aca7177c2c6f8c06eef7d17fd038848875344babe16c1a6de790e9516f"
    url = "https://github.com/JuliaBinaryWrappers/XyceWrapper_jll.jl/releases/download/XyceWrapper-v0.1.1+0/XyceWrapper.v0.1.1.x86_64-linux-gnu-cxx11.tar.gz"
[[XyceWrapper]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c19f14115abf57f947d87061b04f648dbf0ea5a9"
libc = "musl"
os = "linux"

    [[XyceWrapper.download]]
    sha256 = "5c15d42de8be834e16d1dd5746df62187cbcdf1c18cfc1c52ddd8ad9175a9ac4"
    url = "https://github.com/JuliaBinaryWrappers/XyceWrapper_jll.jl/releases/download/XyceWrapper-v0.1.1+0/XyceWrapper.v0.1.1.x86_64-linux-musl-cxx03.tar.gz"
[[XyceWrapper]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "45d02283b8ec3f36b17256e3134d422a3750e81a"
libc = "musl"
os = "linux"

    [[XyceWrapper.download]]
    sha256 = "6fd13806a80b98639f4152f7430c659426db70933bc9c0f8cd52660e4315b68d"
    url = "https://github.com/JuliaBinaryWrappers/XyceWrapper_jll.jl/releases/download/XyceWrapper-v0.1.1+0/XyceWrapper.v0.1.1.x86_64-linux-musl-cxx11.tar.gz"
