[[XyceWrapper]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1e01b6b5aeacf9579536972489e2880f15035633"
libc = "glibc"
os = "linux"

    [[XyceWrapper.download]]
    sha256 = "f4e87a06534ee86299bdd0d0041498057bac7b9dfdda3326613adb513cce3ed5"
    url = "https://github.com/JuliaBinaryWrappers/XyceWrapper_jll.jl/releases/download/XyceWrapper-v0.1.0+0/XyceWrapper.v0.1.0.aarch64-linux-gnu-cxx03.tar.gz"
[[XyceWrapper]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3d34f4128eed60765d31a2b691c22b9864242d7c"
libc = "glibc"
os = "linux"

    [[XyceWrapper.download]]
    sha256 = "5c410b6f3b90b0d0e897d83ae449ca80e24c60ad98007f8fd8756f57ec4eaee6"
    url = "https://github.com/JuliaBinaryWrappers/XyceWrapper_jll.jl/releases/download/XyceWrapper-v0.1.0+0/XyceWrapper.v0.1.0.aarch64-linux-gnu-cxx11.tar.gz"
[[XyceWrapper]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e8842661d9174eae4d070488afc6f9d62c9e9751"
libc = "musl"
os = "linux"

    [[XyceWrapper.download]]
    sha256 = "bbf224739911045b5b0fb0dbc349cc6bf660ee050514ca49440fb760a39e4e41"
    url = "https://github.com/JuliaBinaryWrappers/XyceWrapper_jll.jl/releases/download/XyceWrapper-v0.1.0+0/XyceWrapper.v0.1.0.aarch64-linux-musl-cxx03.tar.gz"
[[XyceWrapper]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "47e6d48719f0ae7aab5346ac7ff7eae85a201671"
libc = "musl"
os = "linux"

    [[XyceWrapper.download]]
    sha256 = "ef14cce46d1e75d4c798ce439e17e6a24b9af7b812d601fd620b730ca55bd711"
    url = "https://github.com/JuliaBinaryWrappers/XyceWrapper_jll.jl/releases/download/XyceWrapper-v0.1.0+0/XyceWrapper.v0.1.0.aarch64-linux-musl-cxx11.tar.gz"
[[XyceWrapper]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b73679b801f51f6d012ad0cb1e9ba93473f6c53d"
libc = "glibc"
os = "linux"

    [[XyceWrapper.download]]
    sha256 = "c26331026f17ed9ddfcd3758402f25103978274f10c19aa9351de8c7335b50bb"
    url = "https://github.com/JuliaBinaryWrappers/XyceWrapper_jll.jl/releases/download/XyceWrapper-v0.1.0+0/XyceWrapper.v0.1.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[XyceWrapper]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f4bbae80907d70878da3805f9e74d4d9dc2c46e6"
libc = "glibc"
os = "linux"

    [[XyceWrapper.download]]
    sha256 = "572234c000de54fb91f088aa394c77c896ca8858e76a5bd46788e20dbeecb57d"
    url = "https://github.com/JuliaBinaryWrappers/XyceWrapper_jll.jl/releases/download/XyceWrapper-v0.1.0+0/XyceWrapper.v0.1.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[XyceWrapper]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f6cafe43285b776cf0c8f79e7316d60a861743c7"
libc = "musl"
os = "linux"

    [[XyceWrapper.download]]
    sha256 = "0a662fe660a550d18223f7809e345785cdc7dea2b2bc5c2742caa61bd9770bc7"
    url = "https://github.com/JuliaBinaryWrappers/XyceWrapper_jll.jl/releases/download/XyceWrapper-v0.1.0+0/XyceWrapper.v0.1.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[XyceWrapper]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "30a8680e78c213d1c72732e4771d91457b1ed717"
libc = "musl"
os = "linux"

    [[XyceWrapper.download]]
    sha256 = "4419a826d400ed821672f59a6b3fde749256e40e4b22b127c5a7c2c453fdf03b"
    url = "https://github.com/JuliaBinaryWrappers/XyceWrapper_jll.jl/releases/download/XyceWrapper-v0.1.0+0/XyceWrapper.v0.1.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[XyceWrapper]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "dad0ff5644dc45a3d5f181ed0b5cba58abbcb7ff"
libc = "glibc"
os = "linux"

    [[XyceWrapper.download]]
    sha256 = "011609713e03a7d10e88e85787763cd8acd70498dc79793e75b1d8718177ec39"
    url = "https://github.com/JuliaBinaryWrappers/XyceWrapper_jll.jl/releases/download/XyceWrapper-v0.1.0+0/XyceWrapper.v0.1.0.i686-linux-gnu-cxx03.tar.gz"
[[XyceWrapper]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1e01213629d0dafc6e62d54cd62a67b07c11ad0c"
libc = "glibc"
os = "linux"

    [[XyceWrapper.download]]
    sha256 = "5574ba7142d14ddcc8ac49ea23361f04a829685bf8b67d4e565be8af4796670f"
    url = "https://github.com/JuliaBinaryWrappers/XyceWrapper_jll.jl/releases/download/XyceWrapper-v0.1.0+0/XyceWrapper.v0.1.0.i686-linux-gnu-cxx11.tar.gz"
[[XyceWrapper]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e00ea5b3e9c88c9131e852a3f27f73448290dc73"
libc = "glibc"
os = "linux"

    [[XyceWrapper.download]]
    sha256 = "21eb84f6f36b319fe3f2f055013be60dd7121fb50d8a0cfe2e8a9174625e0403"
    url = "https://github.com/JuliaBinaryWrappers/XyceWrapper_jll.jl/releases/download/XyceWrapper-v0.1.0+0/XyceWrapper.v0.1.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[XyceWrapper]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a8eec5753a35c6c0550717d4da006a1e96222033"
libc = "glibc"
os = "linux"

    [[XyceWrapper.download]]
    sha256 = "51e25c5304f0241f143c796a5e9f5d21ce9c768322fcb96754b65e954f82d3cc"
    url = "https://github.com/JuliaBinaryWrappers/XyceWrapper_jll.jl/releases/download/XyceWrapper-v0.1.0+0/XyceWrapper.v0.1.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[XyceWrapper]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6ee017ecf2b8fdccb2000876a0ca5dae7584b5c4"
libc = "glibc"
os = "linux"

    [[XyceWrapper.download]]
    sha256 = "e2d828f5659255546f0680a8fe7ba486ad9c58b5ef43da5b572121f3e51152be"
    url = "https://github.com/JuliaBinaryWrappers/XyceWrapper_jll.jl/releases/download/XyceWrapper-v0.1.0+0/XyceWrapper.v0.1.0.x86_64-linux-gnu-cxx03.tar.gz"
[[XyceWrapper]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "271679770739b9d28d0bd7e313f6123b43f1bafb"
libc = "glibc"
os = "linux"

    [[XyceWrapper.download]]
    sha256 = "a0d0e741b09051cb20638d9a2fe975e4121ed2b30f6c930950160db0ec23b9fd"
    url = "https://github.com/JuliaBinaryWrappers/XyceWrapper_jll.jl/releases/download/XyceWrapper-v0.1.0+0/XyceWrapper.v0.1.0.x86_64-linux-gnu-cxx11.tar.gz"
[[XyceWrapper]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "cae4e78d9d0f63f41ef2e46a2555548fc777c548"
libc = "musl"
os = "linux"

    [[XyceWrapper.download]]
    sha256 = "ecd5827b643857914892b888664396e47059ff2cf119f4cb769a6c79010e059d"
    url = "https://github.com/JuliaBinaryWrappers/XyceWrapper_jll.jl/releases/download/XyceWrapper-v0.1.0+0/XyceWrapper.v0.1.0.x86_64-linux-musl-cxx03.tar.gz"
[[XyceWrapper]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "abe606cef856495f02278e398423d18dee7c4bac"
libc = "musl"
os = "linux"

    [[XyceWrapper.download]]
    sha256 = "d91ade3285a4829e28888964e91de1106f77bacb0914bf0ccd792038b1bfea26"
    url = "https://github.com/JuliaBinaryWrappers/XyceWrapper_jll.jl/releases/download/XyceWrapper-v0.1.0+0/XyceWrapper.v0.1.0.x86_64-linux-musl-cxx11.tar.gz"
